SupportModel/src/objects/Model__c.object
<CustomObject>
    <description>Model object is used to give user option to enter details related to Incidents and Service Requests</description>
    <fields>
        <fullName>Contract_Start_Date__c</fullName>
        <description>Planned Start Date of the project</description>
        <label>Contract Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Model</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Model</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SupportModel/src/objects/ResourceLoading__c.object
<CustomObject>
    <fields>
        <fullName>Base_Location__c</fullName>
        <label>Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Offshore - INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days__c</fullName>
        <formula>End_Date__c  -  Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FTE_Jan__c</fullName>
        <label>FTE Jan</label>
        <summarizedField>Year__c.Jan__c</summarizedField>
        <summaryFilterItems>
            <field>Year__c.Year__c</field>
            <operation>equals</operation>
            <value>Year1</value>
        </summaryFilterItems>
        <summaryForeignKey>Year__c.ResourceLoadingId__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>GCM_Level__c</fullName>
        <label>GCM Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loading__c</fullName>
        <label>Loading%</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>70</fullName>
                </value>
                <value>
                    <fullName>80</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <referenceTo>Model__c</referenceTo>
        <relationshipLabel>ResourceLoadings</relationshipLabel>
        <relationshipName>ResourceLoadings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate_Hr__c</fullName>
        <label>Rate/Hr</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Salesforce Project Management</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Lead (Salesforce, Force.com, Integration)</fullName>
                </value>
                <value>
                    <fullName>Salesforce Consultant/ Sr Architect</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Lead (Salesforce, Force.com, Integration, Data Migration)</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Analyst (Salesforce, Force.com, Integration, Data Migration)</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Analyst (Salesforce, Force.com, Integration, Data Migration) - On Call</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Analyst (Salesforce, Force.com, Integration, Data Migration)- Off hours</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support Analyst (Salesforce, Force.com, Integration, Data Migration) - Weekends</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Select__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Select</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Fee__c</fullName>
        <formula>Rate_Hr__c  *  Days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>ResourceLoading</label>
    <nameField>
        <displayFormat>RL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ResourceLoadings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SupportModel/src/objects/Year__c.object
<CustomObject>
    <description>This Object will act as the child object of the Resource Loadind and utilized to generate Yearly chart for resource loading Data.</description>
    <fields>
        <fullName>Apr__c</fullName>
        <label>Apr</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aug__c</fullName>
        <label>Aug</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dec__c</fullName>
        <label>Dec</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FTE_Jan__c</fullName>
        <formula>ResourceLoadingId__r.FTE_Jan__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FTE Jan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Feb__c</fullName>
        <label>Feb</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jan__c</fullName>
        <label>Jan</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jul__c</fullName>
        <label>Jul</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jun__c</fullName>
        <label>Jun</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mar__c</fullName>
        <label>Mar</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nov__c</fullName>
        <label>Nov</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oct__c</fullName>
        <label>Oct</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ResourceLoadingId__c</fullName>
        <label>ResourceLoadingId</label>
        <referenceTo>ResourceLoading__c</referenceTo>
        <relationshipLabel>Years</relationshipLabel>
        <relationshipName>Years</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sept__c</fullName>
        <label>Sept</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year#</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Year1</fullName>
                </value>
                <value>
                    <fullName>Year2</fullName>
                </value>
                <value>
                    <fullName>Year3</fullName>
                </value>
                <value>
                    <fullName>Year4</fullName>
                </value>
                <value>
                    <fullName>Year5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Year</label>
    <nameField>
        <displayFormat>Y-{0000000}</displayFormat>
        <label>Year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SupportModel/src/classes/ResourceLoadingRec.cls
public with sharing class ResourceLoadingRec{  

//To display set of resource records related to a Support Model in a table    
@AuraEnabled
 public static list < ResourceLoading__c > fetchResource(String recordId) {
     
       system.debug('rec id list '+recordId);
  list < ResourceLoading__c > returnResList = new List < ResourceLoading__c > ();
 
  List < ResourceLoading__c > lstRes = [Select Id,model__r.name,model__r.Contract_Start_Date__c,FTE_Jan__c,CreatedById,Days__c,End_Date__c,GCM_Level__c,LastModifiedById,Loading__c,Base_Location__c,Model__c,Rate_Hr__c,Name,Role__c,Select__c,Start_Date__c,Total_Fee__c
 FROM ResourceLoading__c Where Model__c =:recordId];  
  for (ResourceLoading__c r: lstRes) {
   returnResList.add(r);
  }
 // return the List of resource records
  return returnResList;
 }
  
 
    
//To display years data  
@AuraEnabled
 public static list < Year__c > fetchYears(String yearsel, String recordId) {  
     
       system.debug('rec id list years '+recordId+  'year selected 1252  '+ yearsel);        
  list < Year__c > returnYrsList = new List < Year__c > ();  
 
  List < Year__c > lstYrs = [Select Id, ResourceLoadingId__r.model__r.name, ResourceLoadingId__r.Role__c,FTE_Jan__c, Year__c, Jan__c, Feb__c, 
                             Mar__c, Apr__c, May__c, Jun__c, Jul__c, Aug__c, Sept__c, Oct__c, Nov__c, Dec__c  
 							FROM Year__c Where ResourceLoadingId__r.model__c =:recordId and toLabel(Year__c) =: yearsel];              
  for (Year__c y: lstYrs) {     
   returnYrsList.add(y);  
  }
 // return the List of resource year records  
  return returnYrsList;  
 }    
    
//To add resource record    
@AuraEnabled
public static ResourceLoading__c saveRes (ResourceLoading__c res, String recordId) {
    system.debug('rec id '+recordId);
  Model__c m1= [Select Id,name,Contract_Start_Date__c FROM Model__c Where Id =:recordId limit 1]; 
    System.debug('contract start date '+m1.Contract_Start_Date__c);
    Date CtDate=m1.Contract_Start_Date__c;

    Date Stdt=res.Start_Date__c;
    Date Edt=res.End_Date__c;
    
    system.debug('Stdt '+Stdt+' CtDate '+ CtDate);  
    
     if(Stdt > Edt)  
    {
        throw new AuraHandledException('Start date can not be after End Date');             
    }
    if(Stdt < CtDate)
    {
        throw new AuraHandledException('Resource start date can not be before Contract Start Date');         
    }
    
res.Model__c=recordId;     
upsert res;
return res;  
}

//To delete Resource records    
@AuraEnabled
 public static List < String > deleteRecords(List < String > lstRecordId) {
  // for store Error Messages  
  List < String > oErrorMsg = new List < String > ();
  // Query Records for delete where id in lstRecordId [which is pass from client side controller] 
  List < ResourceLoading__c > lstDeleteRec = [select Id from ResourceLoading__c where id IN: lstRecordId];
  
  // delte Resource list with Database.DeleteResult[] database class.
  // It deletes some queried Resource using <samp class="codeph apex_code">Database.<span class="statement">delete</span></samp> 
  // with a false second parameter to allow partial processing of records on failure.
  // Next, it iterates through the results to determine whether the operation was successful or not
  // for each record. and check if delete Resource successful so print msg on debug, 
  // else add error message to oErrorMsg List and return the list  
  Database.DeleteResult[] DR_Dels = Database.delete(lstDeleteRec, false);
  // Iterate through each returned result
  for (Database.DeleteResult dr: DR_Dels) {
   if (dr.isSuccess()) {
      system.debug('successful delete Resource');
     // Operation was successful
   } else {
    // Operation failed, so get all errors   
    oErrorMsg.add('');
    for (Database.Error err: dr.getErrors()) {
     // add Error message to oErrorMsg list and return the list
     oErrorMsg.add(err.getStatusCode() + ': ' + err.getMessage());
    }
   }
  }
  return oErrorMsg;    
 
 }    
    
    
    //To display set of resource records related to a Support Model in a table    
@AuraEnabled
 public static Model__c GetModel(String recordId) {
     
       system.debug('rec id in GetStartDate '+recordId);   
     
     Model__c m= [Select Id,name,Contract_Start_Date__c FROM Model__c Where Id =:recordId limit 1]; 
System.debug('contract start date '+m.Contract_Start_Date__c);
 // return the List of resource records
  return m; 
 }
    
}